### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by panchicore** [panchicore/es-gdelt#1]
- python scripts
- elasticsearch indexes
- logstash pipelines

**Comment by hamzahkhan** [comment]
Hey,
Needed some help. Are you guys still active?

**Comment by panchicore** [comment]
hi @hamzahkhan, is still active and working, its collecting data, I moved this process to a pipeline process with apache nifi so I could create a realtime alert system before indexing in ES, it was using too much space within a period of 6 months, so moved to pre-process and store what we needed. Feel free to contribute with whatever you need/want. Thanks for reaching out.

**Comment by hamzahkhan** [comment]
Thanks for the swift response. I am really new to ES tech stack. If I had to implement a pipeline to index Gdelt in ES..where do I start? Maybe using your code or something else. Some suggestions will really help.

**Comment by panchicore** [comment]
I just added quick instructions in the README file.

**Comment by hamzahkhan** [comment]
Thanks man
